[build]
  command = "npm run build"
  publish = "public"
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "script-src 'self' 'unsafe-inline' www.google-analytics.com dev-api.ossn.club backend.ossn.club https:"
[[headers]]
  for = "*.svg"
  [headers.values]
    Content-Type = "image/svg+xml; charset=utf-8"
[[redirects]]
  from = "https://dev.ossn.club/api/*"
  to = "https://dev-api.ossn.club/api/:splat"
  status = 200
[[redirects]]
  from = "/api/*"
  to = "https://backend.ossn.club/api/:splat"
  status = 200
[context.production]
  environment = { ENV = "PRODUCTION", NODE_ENV = "PRODUCTION"}
[context.deploy-preview]
  environment = { ENV = "PREVIEW", NODE_ENV = "PRODUCTION"}
[context.branch-deploy]
  environment = { ENV = "DEVELOP", NODE_ENV = "PRODUCTION"}
